version: 2.1
orbs:
  node: circleci/node@1.1.6
  react: thefrontside/react@0.2.0
  eslint: arrai/eslint@1.3.0
  


jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
  push:
    jobs:
      - react/install
      - react/eslint:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install
      - react/coverage:
          requires:
            - react/install
      - eslint
